%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    C:\Users\Zhongxu\Documents\myStudy\picpairfMRI\matlabFunctions\picpairSubjInfo.xlsx
%    Worksheet: Sheet1
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2014/01/20 10:41:16

%% Import the data
[~, ~, subInfoData] = xlsread('C:\Users\Zhongxu\Documents\myStudy\picpairfMRI\matlabFunctions\picpairSubjInfo.xlsx','Sheet1');
subInfoData(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),subInfoData)) = {' '};

preRest.emotion(4:20) = cell2mat(subInfoData(5:end,20));
preRest.emotion(1:3) = mean(cell2mat(subInfoData(5:end,20)));
preRest.vividness(4:20) = cell2mat(subInfoData(5:end,21));
preRest.vividness(1:3) = mean(cell2mat(subInfoData(5:end,21)));
preRest.past = cell2mat(subInfoData(2:end,11));
preRest.future= cell2mat(subInfoData(2:end,12));


thinkAheadRest.emotion = cell2mat(subInfoData(2:end,36));
thinkAheadRest.vividness= cell2mat(subInfoData(2:end,35));
thinkAheadRest.past = cell2mat(subInfoData(2:end,31));
thinkAheadRest.future= cell2mat(subInfoData(2:end,32));

thinkBackRest.emotion = cell2mat(subInfoData(2:end,29));
thinkBackRest.vividness= cell2mat(subInfoData(2:end,28));
thinkBackRest.past = cell2mat(subInfoData(2:end,24));
thinkBackRest.future= cell2mat(subInfoData(2:end,27));

iDThinkTaskAtRest= find((cell2mat(subInfoData(2:end,16))+cell2mat(subInfoData(2:end,16)))~=0)';

    iDThinkTaskAtRest1=zeros(1,20);
    iDThinkTaskAtRest1(8)=1;
    iDThinkTaskAtRest2=zeros(1,20);
    iDThinkTaskAtRest2(8)=13;