

%-----------------------------------------------------------------------
dataDir = 'C:\Users\Zhongxu\Documents\myStudy\picpairfMRI\secondLevelAnalysis\picEffect_Pic-Scramble\';
faceDir = 'C:\Users\Zhongxu\Documents\myStudy\picpairfMRI\secondLevelAnalysisLocalizer\face-house\';
houseDir = 'C:\Users\Zhongxu\Documents\myStudy\picpairfMRI\secondLevelAnalysisLocalizer\house-face-object\';
matlabbatch{1}.spm.util.imcalc.input = {[dataDir,'L_TMP.img'];...
                                        [dataDir,'R_TMP.img'];...
                                        [dataDir,'L_vmP.img'];...
                                        [dataDir,'R_vmP.img'];...
                                        [dataDir,'L_HPC.img'];...
                                        [dataDir,'R_HPC.img'];...
                                        [houseDir,'L_PPA.img'];...
                                        [houseDir,'R_PPA.img'];...
                                        [faceDir,'L_FFA.img'];...
                                        [faceDir,'R_FFA.img']};
matlabbatch{1}.spm.util.imcalc.output = ['allFunctionalROI'];
matlabbatch{1}.spm.util.imcalc.outdir = {dataDir};
matlabbatch{1}.spm.util.imcalc.expression = '4*(logical(i1 + i2))+ 5*(logical(i3 + i4)) + 3*(logical(i5 + i6)) + 1*(logical(i7 + i8)) + 2*(logical(i9 + i10))';
matlabbatch{1}.spm.util.imcalc.options.dmtx = 0;
matlabbatch{1}.spm.util.imcalc.options.mask = -1; % very important!!!! if not set to zero, calculation will fail because nan cannot be computed with other numerical or logical numbers
matlabbatch{1}.spm.util.imcalc.options.interp = 1;
matlabbatch{1}.spm.util.imcalc.options.dtype = 4;

spm('defaults', 'FMRI');
spm_jobman('run',matlabbatch);

